#!/bin/sh
#
# Starts inetsim as a system service.
#

start() {
    INETSIM_ARGS="$INETSIM_ARGS"

    printf "Started inetsim: "
    umask 077

    start-stop-daemon -S -qb -p /var/run/inetsim.pid \
        --exec /usr/bin/inetsim -- "${INETSIM_ARGS}"
    
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping inetsim: "
    start-stop-daemon -K -q --retry 20/KILL -p /var/run/inetsim.pid
}

restart() {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?